name: Executar script Python

on:
  schedule:
    # Roda a cada dia às 6 da manhã (horário de Brasília)
    - cron: '0 9 * * *'

  # Permite rodar o workflow manualmente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Executar script Python
        run: python main.py
